#!/bin/bash
set -eu
NAME="homeport.${HOMEPORT_INTERNAL_NAME}"

if [[ -z "${DOMAIN:-}" ]]; then
  ask_for "What domain would you like to run this vault for?"
  DOMAIN=${HOMEPORT_INTERNAL_LAST_VALUE}
fi
DOMAIN=${DOMAIN#vault.}

CERTS=$(mktemp -d home.ports.XXXXXXXX)
trap "rm -rf $CERTS" EXIT TERM INT

mkdir -p data/etc/tls
openssl req \
  -newkey rsa:4096 -nodes -sha256 \
  -keyout data/etc/tls/key.pem \
  -x509 -days 3650 \
  -subj "/O=Homeport/CN=vault.$DOMAIN" \
  -out data/etc/tls/cert.pem

(docker kill $NAME || true
 docker rm   $NAME || true) 2>/dev/null

docker run -d \
  --name homeport.$NAME \
  --cap-add=IPC_LOCK \
  -p 8200:8200 \
  -v ${PWD}/data/etc/tls:/u/etc/tls \
  $HOMEPORT_INTERNAL_IMAGE
