---
groups: []
resources:
  - name: source
    type: git
    source:
      uri:    git@github.com:homeports/vault-port
      branch: master
      private_key: (( vault "secret/ci/homeports/vault-port/deploy:private" ))
  - name: dockerhub
    type: docker-image
    source:
      repository: homeports/vault
      tag:        latest
      username:   (( vault "secret/dockerhub:username" ))
      password:   (( vault "secret/dockerhub:password" ))

jobs:
  - name: build
    plan:
      - get: source
        trigger: true

      - task: prepare
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: starkandwayne/concourse
              tag: latest
          inputs:  [name: source]
          outputs: [name: cached]
          run:
            path: source/ci/try-build
            args: []
          params:
            IN:  source
            OUT: cached/docker

      - put: dockerhub
        params:
          build: cached/docker
          tag_as_latest: true
